# Creates a scylla cluster with 6 nodes and 2 datacenters
# Each node has 2 shards
#
# DC1:
#   node1 - 172.18.0.11
#   node2 - 172.18.0.12
#   node3 - 172.18.0.13
#
# DC2:
#   node4 - 172.18.0.14
#   node5 - 172.18.0.15
#   node6 - 172.18.0.16

version: "3"

services:
    node1:
        image: scylladb/scylla
        command: --seeds=node1,node2,node3,node4,node5,node6 --smp 2 --memory 1G --api-address 0.0.0.0
        volumes:
            - "./config/dc1.properties:/etc/scylla/cassandra-rackdc.properties:ro"
            - "./config/scylla.yaml:/etc/scylla/scylla.yaml:ro"
        networks:
          cluster-net:
            ipv4_address: 172.18.0.11
    
    node2:
        image: scylladb/scylla
        command: --seeds=node1,node2,node3,node4,node5,node6 --smp 2 --memory 1G --api-address 0.0.0.0
        volumes:
            - "./config/dc1.properties:/etc/scylla/cassandra-rackdc.properties:ro"
            - "./config/scylla.yaml:/etc/scylla/scylla.yaml:ro"
        networks:
            cluster-net:
                ipv4_address: 172.18.0.12

    node3:
        image: scylladb/scylla
        command: --seeds=node1,node2,node3,node4,node5,node6 --smp 2 --memory 1G --api-address 0.0.0.0
        volumes:
            - "./config/dc1.properties:/etc/scylla/cassandra-rackdc.properties:ro"
            - "./config/scylla.yaml:/etc/scylla/scylla.yaml:ro"
        networks:
            cluster-net:
                ipv4_address: 172.18.0.13
    
    node4:
        image: scylladb/scylla
        command: --seeds=node1,node2,node3,node4,node5,node6 --smp 2 --memory 1G --api-address 0.0.0.0
        volumes:
            - "./config/dc2.properties:/etc/scylla/cassandra-rackdc.properties:ro"
            - "./config/scylla.yaml:/etc/scylla/scylla.yaml:ro"
        networks:
            cluster-net:
                ipv4_address: 172.18.0.14
    
    node5:
        image: scylladb/scylla
        command: --seeds=node1,node2,node3,node4,node5,node6 --smp 2 --memory 1G --api-address 0.0.0.0
        volumes:
            - "./config/dc2.properties:/etc/scylla/cassandra-rackdc.properties:ro"
            - "./config/scylla.yaml:/etc/scylla/scylla.yaml:ro"
        networks:
            cluster-net:
                ipv4_address: 172.18.0.15

    node6:
        image: scylladb/scylla
        command: --seeds=node1,node2,node3,node4,node5,node6 --smp 2 --memory 1G --api-address 0.0.0.0
        volumes:
            - "./config/dc2.properties:/etc/scylla/cassandra-rackdc.properties:ro"
            - "./config/scylla.yaml:/etc/scylla/scylla.yaml:ro"
        networks:
            cluster-net:
                ipv4_address: 172.18.0.16

networks:
  cluster-net:
    driver: bridge
    ipam:
        driver: default
        config:
        - subnet: 172.18.0.1/24